# MER: Multiple Erosion Rates
MODEL:
  ARCHITECTURE: unet_3d
  BLOCK_TYPE: residual_se
  OUT_PLANES: 9
  TARGET_OPT: ["2", "2", "2"]
  LABEL_EROSION: [1, 2, 4]
  LOSS_OPTION:
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
  LOSS_WEIGHT: [[1.0, 0.5], [1.0, 0.5], [1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"], ["1", "0"], ["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"], ["none", "sigmoid"], ["none", "sigmoid"]]
DATASET:
  OUTPUT_PATH: outputs/Zebrafinch_UNet_MER
INFERENCE:
  OUTPUT_ACT: ["sigmoid", "sigmoid", "sigmoid"]
  OUTPUT_PATH: outputs/Zebrafinch_UNet_MER/test
