SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 16
MODEL:
  ARCHITECTURE: deeplabv3c
  BACKBONE: resnet101
  AUX_OUT: True
  INPUT_SIZE: [1, 513, 513]
  OUTPUT_SIZE: [1, 513, 513]
  IN_PLANES: 1
  OUT_PLANES: 5
  TARGET_OPT: ["0-1-2-3-4-5", "0-2", "0-3", "0-4", "0-5"]
  LOSS_OPTION:
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
  LOSS_WEIGHT: [[1.0, 0.5], [1.0, 0.5], [1.0, 0.5], [1.0, 0.5], [1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"], ["1", "0"], ["1", "0"], ["1", "0"], ["1", "0"]]
  OUTPUT_ACT:
    - - none
      - sigmoid
    - - none
      - sigmoid
    - - none
      - sigmoid
    - - none
      - sigmoid
    - - none
      - sigmoid
  NORM_MODE: gn
  MIXED_PRECESION: True
DATASET:
  INPUT_PATH: datasets/SingleCell/
  IMAGE_NAME: train_image/*.tif
  LABEL_NAME: train_label/*.tif
  OUTPUT_PATH: outputs/SingleCell_Deeplab/
  PAD_SIZE: [0, 0, 0]
  DATA_SCALE: [1.0, 0.5, 0.5]
  REJECT_SAMPLING:
    SIZE_THRES: 5000
    P: 1.0
  DISTRIBUTED: True
  DO_2D: True
  LOAD_2D: True
AUGMENTOR:
  SMOOTH: False
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 4
MONITOR:
  ITERATION_NUM: [40, 400]
INFERENCE:
  INPUT_SIZE: [1, 513, 513]
  OUTPUT_SIZE: [1, 513, 513]
  OUTPUT_ACT: ["sigmoid", "sigmoid", "sigmoid", "sigmoid", "sigmoid"]
  IMAGE_NAME: datasets/SingleCell/test_path.txt
  IS_ABSOLUTE_PATH: True
  DO_SINGLY: True
  OUTPUT_PATH: outputs/SingleCell_Deeplab/test/
  OUTPUT_NAME: pred
  PAD_SIZE: [0, 0, 0]
  AUG_NUM: None
  STRIDE: [1, 256, 256]
  SAMPLES_PER_BATCH: 16
  OUTPUT_SCALE: [1.0, 2.0, 2.0]
