# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/defaults.py
SYSTEM:
  NUM_GPUS: 4
  NUM_CPUS: 16
MODEL:
  INPUT_SIZE: [33, 97, 97]
  OUTPUT_SIZE: [33, 97, 97]
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ["2"]
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss", "DiceLoss"]]
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  NORM_MODE: sync_bn
  FILTERS: [32, 64, 96, 128, 192]
DATASET:
  IMAGE_NAME: datasets/zebrafinch/img_train.txt
  LABEL_NAME: datasets/zebrafinch/seg_train.txt
  OUTPUT_PATH: outputs/Zebrafinch/
  IS_ABSOLUTE_PATH: True
  PAD_SIZE: [4, 32, 32]
  DISTRIBUTED: True
  REJECT_SAMPLING:
    DIVERSITY: 3
  DATA_CHUNK_NUM: [20, 7, 8] # only for inference
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 200000
  SAMPLES_PER_BATCH: 2
INFERENCE:
  INPUT_SIZE: [33, 257, 257]
  OUTPUT_SIZE: [33, 257, 257]
  OUTPUT_ACT: ["sigmoid"]
  IS_ABSOLUTE_PATH: False
  DO_CHUNK_TITLE: 1
  INPUT_PATH: datasets/zebrafinch/
  IMAGE_NAME: zebrafinch.json
  OUTPUT_PATH: outputs/Zebrafinch/test
  OUTPUT_NAME: result.h5
  PAD_SIZE: [8, 128, 128]
  AUG_MODE: min
  AUG_NUM: None
  STRIDE: [16, 128, 128]
  SAMPLES_PER_BATCH: 4
