MODEL:
  ARCHITECTURE: 'fpn_3d'
  BACKBONE: 'resnet'
  BLOCK_TYPE: 'residual_se'
DATASET:
  OUTPUT_PATH: 'outputs/CREMI_Binary_FPN_ResNet'
INFERENCE:
  OUTPUT_PATH: 'outputs/CREMI_Binary_FPN_ResNet/test'