# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/defaults.py
SYSTEM:
  NUM_GPUS: 3
  NUM_CPUS: 12
MODEL:
  INPUT_SIZE: [17, 257, 257]
  OUTPUT_SIZE: [17, 257, 257]
  IN_PLANES: 1
  NORM_MODE: sync_bn
DATASET:
  IMAGE_NAME: images/im_A_v2_200.h5@images/im_B_v2_200.h5@images/im_C_v2_200.h5
  LABEL_NAME: gt-syn/syn_A_v2_200.h5@gt-syn/syn_B_v2_200.h5@gt-syn/syn_C_v2_200.h5
  INPUT_PATH: datasets/CREMI/
  OUTPUT_PATH: outputs/CREMI_syn_baseline
  PAD_SIZE: [0, 32, 32]
  REJECT_SAMPLING:
    SIZE_THRES: 1000
    P: 0.95
  DISTRIBUTED: True
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.02
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 150000
  SAMPLES_PER_BATCH: 2
INFERENCE:
  INPUT_SIZE: [17, 257, 257]
  OUTPUT_SIZE: [17, 257, 257]
  OUTPUT_ACT: ["sigmoid"]
  IMAGE_NAME: images/im_A+_v2_200_nocrack.h5@images/im_B+_v2_200.h5@images/im_C+_v2_200.h5
  OUTPUT_PATH: outputs/CREMI_syn_baseline/test
  OUTPUT_NAME: result.h5
  DO_SINGLY: True
  PAD_SIZE: [0, 32, 32]
  AUG_MODE: mean
  AUG_NUM: 8
  STRIDE: [8, 128, 128]
  SAMPLES_PER_BATCH: 8
