SYSTEM:
  NUM_GPUS: 4
  NUM_CPUS: 16
MODEL:
  INPUT_SIZE: [17, 193, 193]
  OUTPUT_SIZE: [17, 193, 193]
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ["2"]
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss", "DiceLoss"]]
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  NORM_MODE: sync_bn
  FILTERS: [32, 64, 96, 128, 192]
DATASET:
  IMAGE_NAME:
    - vol1/im_orig_noPad.h5
    - vol2/im_orig_noPad.h5
    - vol3/im_orig_noPad.h5
    - vol4/im_orig_noPad.h5
  LABEL_NAME:
    - vol1/seg_gt_v2.h5
    - vol2/seg_gt_v2.h5
    - vol3/seg_gt_v2.h5
    - vol4/seg_gt_v2.h5
  INPUT_PATH: datasets/JWR15/roi_8x8x3um/
  OUTPUT_PATH: outputs/JWR15_Neuron/
  DATA_SCALE: [1.0, 2.0, 1.0]
  PAD_SIZE: [2, 48, 48]
  DISTRIBUTED: True
  REJECT_SAMPLING:
    DIVERSITY: 3
  DATA_CHUNK_NUM: [20, 7, 8] # only for inference
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 200000
  SAMPLES_PER_BATCH: 2
INFERENCE:
  INPUT_SIZE: [33, 257, 257]
  OUTPUT_SIZE: [33, 257, 257]
  OUTPUT_ACT: ["sigmoid"]
  IS_ABSOLUTE_PATH: False
  DO_CHUNK_TITLE: 1
  INPUT_PATH: datasets/JWR15/
  IMAGE_NAME: jwr15.json
  OUTPUT_PATH: outputs/JWR15_Neuron/test
  OUTPUT_NAME: result.h5
  PAD_SIZE: [8, 128, 128]
  AUG_MODE: min
  AUG_NUM: None
  STRIDE: [16, 128, 128]
  SAMPLES_PER_BATCH: 4
