MODEL:
  OUT_PLANES: 4
  LOSS_OPTION:
    - - WeightedBCEWithLogitsLoss
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
  LOSS_WEIGHT: [[1.0], [1.0, 0.5]]
  TARGET_OPT: ["2", "4-1-1"]
  WEIGHT_OPT: [["1"], ["1", "0"]]
  OUTPUT_ACT: [["none"], ["none", "sigmoid"]]
DATASET:
  OUTPUT_PATH: outputs/MitoEM_R_AC/
INFERENCE:
  OUTPUT_ACT: ["sigmoid", "sigmoid"]
  OUTPUT_PATH: outputs/MitoEM_R_AC/test/
