MODEL:
  OUT_PLANES: 3
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss"]]
  LOSS_WEIGHT: [[1.0]]
  TARGET_OPT: ["2"]
  WEIGHT_OPT: [["1"]]
  OUTPUT_ACT: [["none"]]
DATASET:
  OUTPUT_PATH: outputs/MitoEM_R_A/
INFERENCE:
  OUTPUT_ACT: ["sigmoid"]
  OUTPUT_PATH: outputs/MitoEM_R_A/test/
